# Generated by Django 3.0.8 on 2020-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
